/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_semo_jnigl_JniIPActivity */

#ifndef _Included_com_semo_jnigl_JniIPActivity
#define _Included_com_semo_jnigl_JniIPActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_semo_jnigl_JniIPActivity_MODE_PRIVATE
#define com_semo_jnigl_JniIPActivity_MODE_PRIVATE 0L
#undef com_semo_jnigl_JniIPActivity_MODE_WORLD_READABLE
#define com_semo_jnigl_JniIPActivity_MODE_WORLD_READABLE 1L
#undef com_semo_jnigl_JniIPActivity_MODE_WORLD_WRITEABLE
#define com_semo_jnigl_JniIPActivity_MODE_WORLD_WRITEABLE 2L
#undef com_semo_jnigl_JniIPActivity_MODE_APPEND
#define com_semo_jnigl_JniIPActivity_MODE_APPEND 32768L
#undef com_semo_jnigl_JniIPActivity_BIND_AUTO_CREATE
#define com_semo_jnigl_JniIPActivity_BIND_AUTO_CREATE 1L
#undef com_semo_jnigl_JniIPActivity_BIND_DEBUG_UNBIND
#define com_semo_jnigl_JniIPActivity_BIND_DEBUG_UNBIND 2L
#undef com_semo_jnigl_JniIPActivity_BIND_NOT_FOREGROUND
#define com_semo_jnigl_JniIPActivity_BIND_NOT_FOREGROUND 4L
#undef com_semo_jnigl_JniIPActivity_CONTEXT_INCLUDE_CODE
#define com_semo_jnigl_JniIPActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_semo_jnigl_JniIPActivity_CONTEXT_IGNORE_SECURITY
#define com_semo_jnigl_JniIPActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_semo_jnigl_JniIPActivity_CONTEXT_RESTRICTED
#define com_semo_jnigl_JniIPActivity_CONTEXT_RESTRICTED 4L
#undef com_semo_jnigl_JniIPActivity_RESULT_CANCELED
#define com_semo_jnigl_JniIPActivity_RESULT_CANCELED 0L
#undef com_semo_jnigl_JniIPActivity_RESULT_OK
#define com_semo_jnigl_JniIPActivity_RESULT_OK -1L
#undef com_semo_jnigl_JniIPActivity_RESULT_FIRST_USER
#define com_semo_jnigl_JniIPActivity_RESULT_FIRST_USER 1L
#undef com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_DISABLE
#define com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_DIALER
#define com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_DIALER 1L
#undef com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_SHORTCUT
#define com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_semo_jnigl_JniIPActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_semo_jnigl_JniIPActivity
 * Method:    nativeOnCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeOnCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_semo_jnigl_JniIPActivity
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeOnPause
  (JNIEnv *, jobject);

/*
 * Class:     com_semo_jnigl_JniIPActivity
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeOnResume
  (JNIEnv *, jobject);

/*
 * Class:     com_semo_jnigl_JniIPActivity
 * Method:    nativeOnDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeOnDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_semo_jnigl_JniIPActivity
 * Method:    nativeInitGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeInitGL
  (JNIEnv *, jobject);

/*
 * Class:     com_semo_jnigl_JniIPActivity
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_semo_jnigl_JniIPActivity
 * Method:    nativeDrawIteration
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeDrawIteration
  (JNIEnv *, jclass, jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeOnTrackballEvent
  (JNIEnv *, jclass, jint,jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeOnTouchEvent
  (JNIEnv *, jclass, jint,jfloat, jfloat);

JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeInitTextureData
  (JNIEnv *, jclass, jintArray, jint, jint);

JNIEXPORT void JNICALL Java_com_semo_jnigl_JniIPActivity_nativeSetTextureData
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
